apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: app-pod
spec:
  selector:
    app: app-pod
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
