apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: k8s-project

---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-sa-token
  namespace: k8s-project
  annotations:
    kubernetes.io/service-account.name: prometheus-sa
    argocd.argoproj.io/tracking-id: k8s-project:/Secret:k8s-project/prometheus-sa-token
type: kubernetes.io/service-account-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-k8s-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
    verbs: ["get"]
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-k8s-role-binding
roleRef:
  kind: ClusterRole
  name: prometheus-k8s-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: prometheus-sa
    namespace: k8s-project
